import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/NavbarWrapper";
import ClientLayout from "@/components/ui/ClientLayout";
import { Syne } from "next/font/google";
//const syne = Syne({ subsets: ["latin"], variable: "--font-syne" });

import { Space_Grotesk } from "next/font/google";

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  variable: "--font-grotesk"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grotesk.variable} font-(--font-grotesk)`}
      >
        <Navbar/>
          {children}
        
      </body>
    </html>
  );
}
